# Generated by Django 2.1.4 on 2018-12-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=64)),
                ('course_price', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('teacher', models.ImageField(upload_to='images/')),
                ('about', models.TextField()),
                ('starting_date', models.DateField()),
            ],
        ),
    ]
